import assert from "node:assert/strict";
import {after,it} from "node:test";
import {ensureProductionOverlay,getProductionOverlay,patchProductionOverlay,setProductionProjectScope,setProductionOverlay,setProductionDiskPersist,undoProductionOverlay,redoProductionOverlay} from "./productionState";
const values=new Map<string,string>();
const priorStorage=Object.getOwnPropertyDescriptor(globalThis,"localStorage");
Object.defineProperty(globalThis,"localStorage",{configurable:true,value:{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value)}});
after(()=>{setProductionProjectScope(null);setProductionOverlay(null,{recordUndo:false});if(priorStorage)Object.defineProperty(globalThis,"localStorage",priorStorage);else Reflect.deleteProperty(globalThis,"localStorage");});
it("isolates cache, active effects and undo for two projects sharing mix-v001",()=>{
 setProductionProjectScope("project-a");
 ensureProductionOverlay("mix-v001");
 patchProductionOverlay({mixId:"mix-v001",volumePointsByTrack:{shared:[{timeMs:0,value:-6}]}});
 setProductionProjectScope("project-b");
 assert.equal(getProductionOverlay(),null);
 assert.deepEqual(ensureProductionOverlay("mix-v001").volumePointsByTrack,{});
 assert.equal(undoProductionOverlay(),null);
 assert.equal(redoProductionOverlay(),null);
 patchProductionOverlay({mixId:"mix-v001",volumePointsByTrack:{shared:[{timeMs:0,value:3}]}});
 setProductionProjectScope("project-a");
 assert.deepEqual(ensureProductionOverlay("mix-v001").volumePointsByTrack.shared,[{timeMs:0,value:-6}]);
 setProductionProjectScope("project-b");
 assert.deepEqual(ensureProductionOverlay("mix-v001").volumePointsByTrack.shared,[{timeMs:0,value:3}]);
});
it("preserves unowned legacy cache without applying it to a new project; disk restore fills its scoped cache",()=>{
 const legacy=JSON.stringify({mixId:"mix-v001",volumePointsByTrack:{shared:[{timeMs:0,value:-12}]}});
 values.set("song-maker:production:mix-v001",legacy);
 setProductionProjectScope("project-new");
 assert.deepEqual(ensureProductionOverlay("mix-v001").volumePointsByTrack,{});
 assert.equal(values.get("song-maker:production:mix-v001"),legacy);
 const fromDisk={...ensureProductionOverlay("mix-v001"),volumePointsByTrack:{shared:[{timeMs:0,value:-2}]}};
 setProductionOverlay(fromDisk,{recordUndo:false});
 setProductionProjectScope(null);setProductionProjectScope("project-new");
 assert.deepEqual(ensureProductionOverlay("mix-v001").volumePointsByTrack.shared,[{timeMs:0,value:-2}]);
});
it("retains the same project's history but drops the previous project's disk writer",()=>{
 setProductionProjectScope("writer-a");ensureProductionOverlay("mix-v001");
 let writesA=0,writesB=0;
 setProductionDiskPersist(()=>{writesA++;});
 patchProductionOverlay({mixId:"mix-v001",volumePointsByTrack:{shared:[{timeMs:0,value:-4}]}});
 setProductionProjectScope("writer-a");
 assert.deepEqual(getProductionOverlay()?.volumePointsByTrack.shared,[{timeMs:0,value:-4}]);
 assert.ok(undoProductionOverlay());
 const beforeSwitch=writesA;
 setProductionProjectScope("writer-b");ensureProductionOverlay("mix-v001");
 patchProductionOverlay({mixId:"mix-v001",volumePointsByTrack:{shared:[{timeMs:0,value:1}]}});
 assert.equal(writesA,beforeSwitch);
 setProductionDiskPersist(()=>{writesB++;});
 patchProductionOverlay({mixId:"mix-v001",volumePointsByTrack:{shared:[{timeMs:0,value:2}]}});
 assert.equal(writesB,1);assert.equal(writesA,beforeSwitch);
});
